### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by Poussinou** [amake/orgro#1]
Hi @amake,

What's the license of this project?

If it's something open-source like the GNU GPL v3 license, we could try to add it to [F-Droid](https://f-droid.org/) after that, if you're ok.

**Comment by amake** [comment]
Sorry it took me a while to think about this. I decided to go with GPLv3. I am interested in publishing to F-Droid, but it may take me a while to get around to it.

**Comment by amake** [comment]
I've posted a merge request to add Orgro to F-Droid:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6798
