### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [amake/orgro#100]
https://monitor.f-droid.org/builds/log/com.madlonkay.orgro/94#site-footer Could you please take a look? Thanks!

**Comment by amake** [comment]
Thanks for the notice. This should be fixed in later versions, for which I just pushed tags.

Do I need to go delete the entry for 1.38.0?
https://gitlab.com/fdroid/fdroiddata/-/blob/d60b385fa404def1e049bc37f688f0d829f1da20/metadata/com.madlonkay.orgro.yml#L573-593

**Comment by linsui** [comment]
I'll fix it. Thanks!
