### ISSUE TITLE
Check box rollup status

### ISSUE THREAD

**Issue by ryflamm** [amake/orgro#102]
Support of the [/] or [%] notations for check list rollup status would be awesome.

**Comment by amake** [comment]
Apparently these are called cookies

https://orgmode.org/manual/Checkboxes.html#Checkboxes-1

**Comment by amake** [comment]
This will be available in v1.46.0, coming soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment]
This is now released on all platforms.
