### ISSUE TITLE
Superscript and subscript support

### ISSUE THREAD

**Issue by llcc** [amake/orgro#109]
Sorry for frequently requesting new features 😄 .

 I've been using Orgro frequently to browse my org-mode files, but there's one thing I'm not satisfied with: the support for superscripts and subscripts in Orgro. Is it possible to add that functionality?

[1] https://www.gnu.org/software/emacs/manual/html_node/org/Subscripts-and-Superscripts.html

**Comment by amake** [comment]
> Sorry for frequently requesting new features 😄 .

No need to apologize. Org Mode has such a huge feature set that no one person can feasibly want everything. So without people pushing me to implement more, Orgro is not likely to improve.

Superscripts and subscripts are coming soon.

**Comment by amake** [comment]
This is implemented in v1.43.1, available for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by llcc** [comment]
Great, works like a charm except for one case from my observation. Normal Greek entities are displayed well but not when they appear in the subscript or superscript.

```org
* subscript and superscript 

\alpha \beta

where_{\alpha}^{\beta}
```

**Comment by amake** [comment]
Entities in {sub,super}scripts will be in v1.43.2.

**Comment by llcc** [comment]
Thanks!
