### ISSUE TITLE
Create a new file

### ISSUE THREAD

**Issue by ydalton** [amake/orgro#110]
My friend introduced me to Orgro, and I'm happy that there is a program (outside of Emacs) that deals with Org documents, and on mobile no less! However, when I tried it out myself, I was disappointed to find there seems to be no way to create a new Org document, which would be my primary use case.

Ideally I would like to implement this myself, but right now I am a Flutter noob (I only have 3 weeks of experience with it).

**Comment by amake** [comment]
This is implemented in v1.43.1, available for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by ydalton** [comment]
Well, I built it myself from source, and it works! Thanks!
