### ISSUE TITLE
Some headline tags not visible when many tags present

### ISSUE THREAD

**Issue by amake** [amake/orgro#111]
> An issue not directly related to this commit, but since you delved into the tags improvement, I would like to bring it up here. Multiple tags are being truncated based on the screen width, and there is no way to view the entire tags. See the example below.
> 
> 
> 
> Org-mode source:
> 
> ```org
> 
> * multiple headline tags  :BAR:FOO:BAZ:タグ:QUX:Archive:
> 
> ```
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/0a1095e5-5c9d-4175-b822-3ee309d9d4b3) 

 _Originally posted by @llcc in [a3795a1](https://github.com/amake/org_parser/commit/a3795a1a348bc0becea0f3294882aeda0b130eb9#commitcomment-147881052)_

**Comment by amake** [comment]
This is ultimately a design problem.

The current implementation tries to show the tags on right, regardless of the width of the screen. This requires that we don't treat the headline as a regular line of text, but rather two boxes that must split the horizontal space according to some rule. Currently that rule is that the tags can take up to 1/3 of the full width. Also, when the section is closed we show an ellipsis.

Closed
![android-1728811189](https://github.com/user-attachments/assets/9c330a7d-e44e-4ca1-94bc-28b3bbf4e8cf)

Open
![android-1728811229](https://github.com/user-attachments/assets/68db8e68-b73f-4b45-aa49-3e0fb88b13f6)

I think it's fairly important to keep the headline to a single line when the section is closed (I do allow the title to wrap, but let's assume a non-wrapping title). So I think the current closed layout is OK. But when open we could stop truncating the tags:

Open (tweak: no truncating)
![image](https://github.com/user-attachments/assets/2229eda3-67f0-4321-97df-68a57926dfdc)

Unfortunately we are now at the mercy of Flutter's internal line breaking logic, which we can't control. This looks like a particularly bad outcome (no idea why it likes to break between タ and グ of all places), but it will depend on the exact text and screen width.

Another possibility is to give up on aligning the tags to the right, and just treat the headline as a single line of text that can wrap. I don't like that idea for Reader Mode, but it's plausible for when Reader Mode is off.

Closed (Reader Mode off; tweak: no fancy layout)
![android-1728825708](https://github.com/user-attachments/assets/706db590-af4c-4b53-94c8-834e8d39c44c)

Open (Reader Mode off; tweak: no fancy layout)
![android-1728825805](https://github.com/user-attachments/assets/f2a53a73-26e0-49ba-8f30-5fb4f6dc6ac4)

Do you generally use Reader Mode? What do you think of the above tweaks?

**Comment by llcc** [comment]
> Do you generally use Reader Mode?
I rarely use Reader Mode, since it reflows the text in the list, which disrupts the multi-line items I use a lot.

When closed, I agree that tags should be truncated. However, how about adding a sliding gesture to view the full tags? While this might conflict with the TODO cycling gesture, we could limit the sliding functionality to only affect the tags.

When open, I personally prefer treating the headline and tags as a normal line without trying to align them, because it breaks versatility if the headline wraps one char to the next line while tags also wrap one. Having them wrap together feels more cohesive. In this case, it might be better to tone down the color of the tags.

What do you think?

**Comment by amake** [comment]
> However, how about adding a sliding gesture to view the full tags?

I think this is a bit too magical and hard to discover.

> When open, I personally prefer treating the headline and tags as a normal line without trying to align them

I do think this is compelling, and I tried making that the behavior for both Reader Mode and non-Reader Mode, but it's too jarring in Reader Mode to go from "fancy" layout to textual layout. 

> it breaks aesthetics if the headline wraps one char to the next line while tags also wrap one.

There are always going to be combinations of content and width that end up with somewhat unfortunate outcomes, so I'm not really that concerned with avoiding that entirely.

> it might be better to tone down the color of the tags.

The colors are org-mode defaults, so I wouldn't change them, but a theme customization feature is something I would consider.

My current thinking is to go with the scheme I described [above](https://github.com/amake/orgro/issues/111#issuecomment-2408979110).

**Comment by amake** [comment]
The changes described above will be available for testing in v1.43.2 soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by llcc** [comment]
The trailing spaces after the headline should be trimmed as one, or the display gets weird on narrow screen.  

```org
* Tags
** Multiple headline tags.         :BAR:FUB:ARCHIVE:DESIGN:EFFORT:FINAL:

Contents
```

![CleanShot 2024-10-15 at 17 38 03@2x](https://github.com/user-attachments/assets/275e3800-2971-4f19-bed0-e7dc4edfd64b)

![CleanShot 2024-10-15 at 17 39 11@2x](https://github.com/user-attachments/assets/fc0f6433-d7fd-4b09-8803-4842a43d4eb7)

**Comment by llcc** [comment]
Yes. It solved part of the issue, but the spaces should still be taken care of. 

Also, the line with : inside begins to display not correctly.

```org
** Multiple headline tags.         :BAR:FUB:ARCHIVE:DESIGN:EFFORT:FINAL:

Contents

- Eq.1: [cite:@canale-2014-harden;see page 5]：
```

![image](https://github.com/user-attachments/assets/11b3f2fe-bf5d-4742-a870-a4e93e06fc9e)

**Comment by llcc** [comment]
> If I remove them then someone will complain that they should be there (when the screen _does_ fit the original assumed width).

How about filling the spaces dynamically (I mean calculating the space number based on the width) for visualization? 

> Does it look different with Reader Mode off?

It's not related to `Reader Mode` from my observation.

> means they wrap as a unit instead of at word or character boundaries.

Not sure if it matters about the paragraph alignment. Orgro left-aligned the paragraph, does it change if we make it justified?

**Comment by amake** [comment]
> How about filling the spaces dynamically (I mean calculating the space number based on the width) for visualization?

This will be in v1.43.4

> Orgro left-aligned the paragraph, does it change if we make it justified?

There are no justification controls. I don't see how justification would change line break locations.

**Comment by amake** [comment]
This is released for all platforms.

**Comment by amake** [comment]
Wrapping of citations will be improved in v1.52.2, ready for testing soon:
 
- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)
