### ISSUE TITLE
Non-ASCII link baseline alignment improvement

### ISSUE THREAD

**Issue by llcc** [amake/orgro#113]
Hi @amake. Thanks again for making Orgro. 

Non-ASCII characters can cause misalignment or inconsistent vertical positioning, leading to the link underline being unnaturally positioned. Please see example below:

```org
- [[https://www.yahoo.co.jp/][日本🇯🇵Yahooニュース]]
- [[https://news.yahoo.co.jp/pickup/6516563][25 年卒の大学生、就職内定率 95.9％]]
```

![CleanShot 2024-10-15 at 18 15 16@2x](https://github.com/user-attachments/assets/fe17ed37-2888-4423-ab08-a02c9e517e7f)

**Comment by amake** [comment]
This is a font issue, and is not really something I can control.

First, the font you have chosen in the ⋮ menu doesn't cover Hanzi or Hiragana, so those fall back to fonts provided by your device. It seems your device is set to prefer to use a Chinese font, so the Hanzi are displayed with that. Then, the Hanzi font doesn't have Kana, so it falls back again to a Japanese font with quite different metrics to the Chinese font.

(My Pixel 2 has Japanese and Chinese fonts that have very similar metrics; probably both Noto.)

There are two main approaches:

1. I can add some additional fonts: M PLUS 1 Code for Japanese, and Noto Sans for Traditional and Simplified Chinese. You would then need to choose the appropriate font for your document.
2. Make sure the locale is set appropriately for the text. For this text, the locale should be Japanese. However Orgro currently has no way of knowing this, so it has to simply assume the default locale of the device. Does the text look better if you set your device to prefer Japanese above all other locales?

    Other than setting the device locale, the appropriate thing is to use an in-band signal. For e.g. HTML there is the [lang attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang); Org Mode has the [LANGUAGE](https://orgmode.org/manual/Export-Settings.html#index-LANGUAGE_002c-keyword) setting. In Emacs this is only used for export, but I could try detecting it here.

**Comment by amake** [comment]
Additional fonts and locale detection will be in v1.43.3, available for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by llcc** [comment]
Yes, works perfectly after I selected `Chivo Mono`.
Thanks for the quick fix.
