### ISSUE TITLE
Editor in light mode too jarring when app in dark mode

### ISSUE THREAD

**Issue by cigumo** [amake/orgro#114]
When editing a document the appearance switches to Light automatically. 
It would be great to stay in dark mode. Maybe an option?

**Comment by amake** [comment]
I have it switch to the opposite mode to make it clear that you're editing.

I don't have a very strong preference for the current behavior, but I do want the editor to be visually distinct from the viewer. I welcome suggestions.

> Maybe an option?

This is very much the kind of thing I would *not* like to offer an option for.

**Comment by cigumo** [comment]
Thanks for getting back, and thanks for the app. 

In my opinion, the top bar changing is more than enough to see the difference. The buttons disappear, the title clearly says editing. You could change the color of the top bar if you want to make it stand out even more. 

The white background is really hurting when editing with low light conditions.

**Comment by amake** [comment]
I've removed the brightness switching and made some other tweaks. The results will be read to test in v1.44.2 soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by cigumo** [comment]
Tested the Testflight build. It's fantastic. Thank you.

**Comment by amake** [comment]
This is now released for all platforms.
