### ISSUE TITLE
Is there a way to use it without Google/Amazon content?

### ISSUE THREAD

**Issue by Plungestep** [amake/orgro#122]
I’m trying to eliminate Google and Amazon content from my life, and this app looks perfect, but apparently pulls fonts from Google and AWS.  Can this be turned off?

**Comment by amake** [comment]
The default font (Fira Code) is bundled with the app. If you never change the font then the app will never attempt to connect to a Google or AWS server.

**Comment by Plungestep** [comment]
That’s an excellent solution and very reasonable!
