### ISSUE TITLE
Support avif image file inline displays

### ISSUE THREAD

**Issue by k4r4b3y** [amake/orgro#124]
First let me say that Orgro is hands-down the best mobile app for reading the org files of mine.  Thanks for creating and maintaining this.

Now, onto the feature request:

I use `.avif` format for my image files.  In debian 12, I simply use `convert image.jpg image.avif` to create these.  Avif files have better compression and therefore take much less space than the their jpg counterparts.  Currently, my avif files linked inside my org mode documents do not get rendered inside Orgro.  Would you consider adding support for rendering .avif files as inline images?

**Comment by amake** [comment]
Thanks for the kind words.

Support for more formats is good; my main concern is not bloating the app install size.

Relevant info:
- https://github.com/flutter/flutter/issues/61229
- https://pub.dev/packages/flutter_avif

**Comment by amake** [comment]
I have basically an allowlist of image file extensions. I will add `.avif` to the list, but actually displaying the image will depend on whether your device's OS supports the AVIF format.

This will be available in v1.50.0, ready for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by k4r4b3y** [comment]
> I will add .avif to the list
Thank you!
> but actually displaying the image will depend on whether your device's OS supports the AVIF format.
I am on latest GrapheneOS release.  Once the Orgro update hits fdroid, I will test whether my OS is able to display inline `.avif` or not.

**Comment by amake** [comment]
It can take weeks to make it into F-Droid, so if you are in any sort of hurry I would suggest [installing from source](https://github.com/amake/orgro?tab=readme-ov-file#get-it).

**Comment by amake** [comment]
This is now released everywhere.

**Comment by k4r4b3y** [comment]
I can confirm that the aivf image files I have in my org mode documents get displayed inline inside orgro app now.  Thank you.
