### ISSUE TITLE
Support Git repo sync

### ISSUE THREAD

**Issue by oskarth** [amake/orgro#14]
I use both Android (tablet) and iOS (phone). I store all my notes in a git repo (not Github) and do most of my editing on my computer. I'd love to be able to pull down an view/edit Org files from mobile/tablet.

**Comment by macdonaldster** [comment]
In the meantime, have you tried Android Git clients like MGit? https://github.com/maks/MGit (available on Play Store, etc). I have tried several clients and found this to be the best one for me.

**Comment by amake** [comment]
I am hoping to keep Orgro focused on viewing org files, and I would like to leave file access to the standard OS APIs (which are already supported) as much as possible. So I am not planning to add anything git-specific to Orgro.

Another Orgro user I believe reported that they had luck opening files in [Working Copy](https://workingcopyapp.com/) for iOS. For Android I checked out MGit and it stores its files in an open location so you can simply browse there: `/Android/data/com.manichord.mgit/files/repos`.

**Comment by oskarth** [comment]
I'll give it a try, thanks! Scope definitely makes sense :)
