### ISSUE TITLE
"Exception: end of input expected" on opening org-file

### ISSUE THREAD

**Issue by mykhas** [amake/orgro#16]
First of all, thanks for the great tool! :)

I've noticed an issue during opening one of my .org-files, saying `Exception: end of input expected at 459:1`. My code for lines 458-459 of related file is:
```
**** TODO [#B] some plain text
*** TODO AB:CD: some more text and =inline code=
```

I'm using iOS version, downloaded from AppStore just a few minutes ago.

**Comment by amake** [comment]
Thanks for the report. That's probably a bug in the org syntax parser. Can you share the file with me? If the content is sensitive you could email it to info at orgro dot org.

**Comment by amake** [comment]
I managed to reproduce with your snippet. It was mistakenly interpreting the `:CD:` as the tag block that can come at the end of the section headline.

It will be fixed in the upcoming release.

Thanks again for your report!

**Comment by amake** [comment]
The fix is available on TestFlight: https://testflight.apple.com/join/8YTxcuZC

**Comment by mykhas** [comment]
Thanks for the fix, Aaron! :)
