### ISSUE TITLE
Support for right-to-left scripts

### ISSUE THREAD

**Issue by oatmealm** [amake/orgro#19]
Hi. Thanks for creating this app!

I was wondering if it'd be possible to allow the text area to reflow the text respecting the script it's written in. Native iOS text areas do this automatically, I think. 

I'll open another issue about serif fonts...

**Comment by amake** [comment]
Orgro is using standard Flutter text widgets, which do support RTL scripts, but I wouldn't be surprised to find that I'm doing something that breaks something. 

Can you please provide

1. A sample org doc using RTL scripts 
2. Screenshots illustrating how it's broken in Orgro
3. If it's something that Emacs gets right, then screenshots of the correct rendering in Emacs

**Comment by oatmealm** [comment]
Hi. Thanks for the reply. 

Yes. Emacs has excellent support for RTL. buffers can be tweaked for reflow using 'bidi-paragraph-direction'. 

I'll get back to you with screenshots and examples ASAP.

**Comment by amake** [comment]
So were there any problems with RTL scripts in Orgro?

**Comment by oatmealm** [comment]
Hi there. Sorry for the delay. The only problem that is really effecting usability right now is the alignment. The flow is correct, but text should be of course aligned to the right end side. See examples.


![2020-08-13 12-07-48-1](https://user-images.githubusercontent.com/68159077/90122783-1eb40500-dd5e-11ea-949f-8e3ab6e6f756.png)

![gnome-shell-screenshot-DKB6O0](https://user-images.githubusercontent.com/68159077/90122743-0fcd5280-dd5e-11ea-82a8-122f03e2adea.png)

**Comment by amake** [comment]
OK thanks. I may be able to do something about that.

Are you able to provide a sample document?

**Comment by amake** [comment]
I'm unable to make progress on this without a sample document, and probably some additional feedback on any fixes I make.

**Comment by dotancohen** [comment]
The problem that I see in both the screenshots and in my installed Orgro is the directionality of the RTL paragraphs. Orgro would need to support different directionality for each paragraph and each heading - e.g. different directionality for each newline-separated string.

I have an explanation of directionality here:
https://dotancohen.com/howto/rtl_right_to_left.html

Basically, RTL directionality will be most obvious in that the text will be right-justified, and also punctuation will show up on the left side of the text.

To test, you can use this text:
שלום, עולם!

The exclamation point should appear on the left of the two words.

**Comment by amake** [comment]
In v1.43.3 I added support for setting the document's locale from the org-mode `#+LANGUAGE:` setting. If you set this to an appropriate value (`he` for Hebrew) then that may improve things.

**Comment by amake** [comment]
This looks correct except for the direction of the `#+` meta lines.

```org
שלום, עולם!

#+LANGUAGE: he
#+FOO: שלום, עולם!

* שלום, עולם!                                                           :foo:

  שלום, עולם!
```
![Screenshot 2024-10-20 at 8 49 16](https://github.com/user-attachments/assets/fa68a360-dc35-4607-b250-42fe76b4a80b)

**Comment by amake** [comment]
There are some constructs that appear to always be LTR even if the content is RTL:

- Keyword lines (`#+LANGUAGE:`, etc.)
- Blocks (`#+begin_example`, etc.)
- More? (needs investigation)

Also I note that lists are LTR or RTL depending on the content of the first item of the list. This is not something I can easily support in Orgro.

**Comment by amake** [comment]
The key is the Emacs behavior around [`bidi-paragraph-direction`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Bidirectional-Editing.html):

- By default it is `nil`, which means the direction of each paragraph is determined by "the first strong directional character of its text". This is difficult to implement in Orgro.
- It can be `right-to-left`. This is equivalent to what Orgro is doing if you provide an RTL locale via `#+LANGUAGE:` in the document, or presumably if your OS is set to prefer an RTL locale.
- It can be `left-to-right`. This is equivalent to what Orgro is doing if you provide an LTR locale via `#+LANGUAGE:` in the document, or presumably if your OS is set to prefer an LTR locale.

**Comment by amake** [comment]
I guess my question is: What value for `bidi-paragraph-direction` do users of RTL languages usually use org-mode with?

**Comment by amake** [comment]
From https://www.reddit.com/r/orgmode/comments/v9nouy/help_org_with_righttoleft_language_defaults/ :

Previously org-mode forcibly set `bidi-paragraph-direction` to `left-to-right`; currently it respects the user's setting.

According to Eli Zaretsky:

> Users of RTL languages are supposed to set `bidi-paragraph-direction` in Org files to `right-to-left`. Leaving the value at `nil` is not only detrimental to performance (even though Emacs 25+ will be faster than older versions), but it also makes the display look ugly, with some of the items beginning at the left margin and some at the right margin.

**Comment by amake** [comment]
Support for auto-detecting text direction on a per-paragraph basis, and honoring `bidi-paragraph-direction` will be in v1.44.0, ready for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by dotancohen** [comment]
RTL users that I know will avoid phrasing a sentence that begins with an English word specifically to avoid such issues - though this is rather easy as few sentences would begin with an English word anyway, and proper nouns are just spelled out in our own letters usually. Therefore it seems that `The direction of each paragraph is determined by "the first strong directional character of its text"` matches user expectation, difficult to implement as it may be.

For what it's worth, of my 535 Org mode files, 230 contain Hebrew and of those, 203 had at least one line of all-English text. Therefore `The direction of each paragraph is determined by "the first strong directional character of its text"` is critical to my workflow.

Thank you!

**Comment by oatmealm** [comment]
In emacs I always set paragraph direction to nil to get automatic realignment. If I need to have some Latin I would either rearrange the sentence or force alignment with one of the non printable codes (sorry forgot what they're called) 

But Arabic/Farsi is a much bigger target IMHO than Hebrew in any case. Would be helping to hear more.

**Comment by amake** [comment]
Thanks for the feedback. By my understanding everything discussed so far is supported in v1.44.0 and later.

**Comment by dotancohen** [comment]
> Thanks for the feedback. By my understanding everything discussed so far is supported in v1.44.0 and later.

Thank you! Aaron!

**Comment by amake** [comment]
This is now released for all platforms.
