### ISSUE TITLE
Improve order of action buttons in app bar

### ISSUE THREAD

**Issue by fountainer** [amake/orgro#23]
I use "Cycle visibility" more frequently than "Change font". However, "Cycle visibility" is hidden, and "Change font" is shown in the top app bar. It's better to allow users to change the order of buttons.

**Comment by amake** [comment]
I'm not really interested in building a UI for customizing the app bar, but it's reasonable to prefer that "Change Visibility" remain visible on narrow screens instead of "Change Font".

**Comment by amake** [comment]
I've adjusted the app bar actions. Test builds for [Android](https://play.google.com/apps/testing/com.madlonkay.orgro) and [iOS](https://testflight.apple.com/join/8YTxcuZC) will be available soon if you want to give some feedback before release.

**Comment by fountainer** [comment]
I tried the test build for iOS. It's better now.
