### ISSUE TITLE
Strikethrough starts and destroys org structure

### ISSUE THREAD

**Issue by thebhgg** [amake/orgro#27]
I've attached a short file which is formatted badly with orgro (but it has a txt extension).  I've also attached a screen shot that shows the strikethrough formatted continuing through a toplevel heading.

[bad_formatting_screenshot](https://user-images.githubusercontent.com/8143851/91613934-86697300-e94e-11ea-840f-2d5d8efc19f5.jpg)

[orgro-bad-format.txt](https://github.com/amake/orgro/files/5144127/orgro-bad-format.txt)

This doesn't happen in emacs or in beorg, and I don't know how to address it here.

**Comment by amake** [comment]
Thank you for the report and the sample. I can confirm the issue. The parser is failing to limit the scope of the `+...+` in the same way that org-mode does. 

I will see about fixing this soon.

**Comment by amake** [comment]
I've put out a new build on [Google Play](https://play.google.com/store/apps/details?id=com.madlonkay.orgro) and [TestFlight](https://testflight.apple.com/join/8YTxcuZC). It's in review, which takes an unpredictable amount of time, so keep an eye out for version 1.11.1.

I did test your sample and it worked for me, but please reopen if necessary.
