### ISSUE TITLE
Support coding systems other than UTF-8

### ISSUE THREAD

**Issue by amake** [amake/orgro#28]
From an App Store review:

> **please add chinese-gbk-dos coding system**
>
> please add chinese-gbk-dos coding system, or any file with Chinese characters will not assign correctly

Chinese characters work fine if the file is encoded with UTF-8, but it would still be better to be able to handle a variety of encodings.

Also `*-dos` files should be handled correctly already.

**Comment by amake** [comment]
I've added encoding auto-detection in v1.12.0. Test builds for [Android](https://play.google.com/apps/testing/com.madlonkay.orgro) and [iOS](https://testflight.apple.com/join/8YTxcuZC) are available.

**Comment by qwfpbj** [comment]
@amake Could you please test if this file works fine on iOS? The update has not been shown on the app store. Thanks very much.
[test_for_non-UTF8.zip](https://github.com/amake/orgro/files/5216480/test_for_non-UTF8.zip)

**Comment by amake** [comment]
I have not released the new version yet; it is available for testing via TestFlight from the link I mentioned above. 

Here is a screenshot of the result for the file you supplied:

![image](https://user-images.githubusercontent.com/2172537/93051963-46212900-f6a0-11ea-8ae0-4be80c9139b1.png)

Please note that the auto-detection is heuristic-based; if the Chinese text doesn't occur until later in the file it might not be detected correctly.

**Comment by qwfpbj** [comment]
Thanks for the prompt reply. That is perfect! All characters and auto detections works well.

**Comment by amake** [comment]
Thanks for confirmation. I'll submit 1.12.0 for release then.
