### ISSUE TITLE
Toggle dark mode on Android 8 and earlier

### ISSUE THREAD

**Issue by fgilbert68** [amake/orgro#29]
On the Google Play store screenshots, I can see a dark mode, but I was unable to find how to switch to it.
Is it really available?
Do I miss something obvious?

Thank you,
F.G.

**Comment by amake** [comment]
It follows the OS setting so just set your system to dark mode and Orgro will follow automatically.

**Comment by fgilbert68** [comment]
Thanks for the answer. This is what I suspected.
Surprisingly, it seems I don't have a "dark mode" on my device (Lenovo Tab4-8, Android 8.1.0).
Unless here again I am missing something, I just have a "night light" setting (making colors going towards amber).

So maybe it could be nice if Orgro dark mode could be activated independently from the app's menu?

**Comment by amake** [comment]
Yeah according to [this](https://www.lifewire.com/what-is-android-dark-mode-4178630) the "official" dark mode is only on Android 9 and later. 

An in-app setting seems reasonable then.

**Comment by amake** [comment]
I just submitted test builds with a new feature: the overflow menu on the top screen now has an "Appearance" item that will let you choose between light, dark, and automatic modes.

The test releases are not yet approved, so keep an eye out:

- [iOS testing](https://testflight.apple.com/join/8YTxcuZC)
- [Android testing](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment]
The test builds are now available.

**Comment by amake** [comment]
This is now released.
