### ISSUE TITLE
LaTeX blocks with tags don't render correctly

### ISSUE THREAD

**Issue by amake** [amake/orgro#42]
As reported in https://github.com/amake/orgro/issues/22#issuecomment-828373842, a LaTeX block with a tag (implied or otherwise) will render with the tag overlapping the main body:

```latex
\begin{equation}
a + b = c
\end{equation}
```

![IMG_1927](https://user-images.githubusercontent.com/5546074/116395064-397bca80-a856-11eb-819e-49c41c75eace.PNG)

**Comment by amake** [comment]
I think it's going to be quite hard to get this to work with all possible layout scenarios:

- LaTeX blocks that are too wide should be allowed to scroll horizontally; in that case, where should the tag go?
- For LaTeX blocks that are narrower than the window, must the tag hug the right side?

Prior to v1.18.0 the `equation` environment was simply dropped, so this was not an issue (the tag was suppressed). Suppressing the tag through some mechanism could be the best solution if people aren't wedded to the tag being shown.

**Comment by amake** [comment]
Things that are easy to do:

- Remove tags entirely
- Show tags at a fixed offset from the right edge of the main content (not aligned to the right of the screen)

**Comment by amake** [comment]
@fountainer Can you comment on what you expect in terms of how tags should be presented?

**Comment by fountainer** [comment]
> @fountainer Can you comment on what you expect in terms of how tags should be presented?

I personally don't care much about the tags. I prefer the solution that tags are removed.

**Comment by fountainer** [comment]
Another option is to put tags on the left of the formulas.

**Comment by amake** [comment]
I think I will go with 

> Show tags at a fixed offset from the right edge of the main content (not aligned to the right of the screen)

and if you don't want tags shown at all then you can use `equation*` instead of `equation`.

**Comment by amake** [comment]
This is addressed in v1.18.1, which is now available in Test Flight.

**Comment by fountainer** [comment]
The equation numbers are always one. Is it a bug?
![IMG_C2645E4E9BD0-1](https://user-images.githubusercontent.com/5546074/116656062-a27e5200-a9be-11eb-8916-518f2d06b9af.jpeg)

**Comment by amake** [comment]
It's a limitation of the current implementation. Each block has its own context, and I don't know how to share the context such that the numbering could continue.

**Comment by amake** [comment]
Actually it seems that it's a limitation of the rendering engine itself. If you want meaningful tags you need to specify the contents manually like `\tag{foo}`.
