### ISSUE TITLE
Grant Access button doesn't work for files opened by intent

### ISSUE THREAD

**Issue by amake** [amake/orgro#43]
> > There are some issues providing access and following the file links on Android 10.
> 
> Could you be more specific?

Sure. The Grant Access buttons (on top and when tapping the actual link) don't seem to do anything.
Tapping the link to an image reports that there is no app which handles the file type.

_Originally posted by @MisterY in https://github.com/amake/orgro/issues/35#issuecomment-833264507_

**Comment by amake** [comment]
I was able to reproduce on Android in the case of opening a file via intent (as opposed to opening a file via the file picker).

It's not possible to resolve links relative to a file opened by intent on Android, because the URI obtained by doing so is not usable with the required APIs.

It may be possible to resolve links in the equivalent iOS scenario, depending on the storage provider (local storage and iCloud may work; third-party apps generally do not work).

I will address this as follows:

1. The Grant Access banner won't be shown if the file is known not to support resolving relative links
2. Better feedback in other scenarios

**Comment by MisterY** [comment]
Oh, I forgot about that detail since the files have been sitting in the list for a long time.

**Comment by amake** [comment]
The changes I described are in v1.18.3 which is out for all platforms. If still nothing happens when tapping Grant Access or there is an error message that seems wrong feel free to reopen.
