### ISSUE TITLE
Regex search via `ugrep --smart-case  --bool`

### ISSUE THREAD

**Issue by NightMachinary** [amake/orgro#49]
`ugrep --smart-case  --bool` is one of the most ergonomic and performant search solutions I have seen. 

PS: https://github.com/Genivia/ugrep is licensed under BSD 3-clause, so it should be usable on iOS (where Apple's monopolistic policies disallow GPL code).

**Comment by amake** [comment]
It's not clear to me what behavior you want to see in Orgro.

Can you explain

- what you want to accomplish
- how the current behavior differs from your desire
