### ISSUE TITLE
Wrongly changing Heading level

### ISSUE THREAD

**Issue by rgshresth** [amake/orgro#51]
I have purchsed Orgro on Android.  When I import an Org file, one specific level-1 Heading (out of 16 level-1 headings) becomes a Level-3 sub-heading of the preceding Level-1 Heading.  The same file imports correctly on Orgzly, showing all the Level-1 Headings.   Not clear why this is happening.

**Comment by amake** [comment]
Probably the parser is not handling it correctly.

Can you provide an org snippet for me to reproduce?

**Comment by amake** [comment]
(Oh and thank you for your purchase. I appreciate it!)

**Comment by amake** [comment]
Thanks for the details. This sounds like https://github.com/amake/org_parser/issues/5. I am working on a fix.

> On an unrelated note, do you plan to add the functionality to open relative links to non-org files (such as PDFs) at some stage?

If I can find a cross-platform way to delegate the opening of such files to the OS, then I would like to add that. But what I don't want to do is add PDF, etc., support to Orgro itself (unless Org Mode has such functionality, in which case it *would* be within scope to incorporate something similar into Orgro).

**Comment by amake** [comment]
The headline parsing issue should be fixed in the next version. You can test a pre-release if you like:

- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)
- [iOS](https://testflight.apple.com/join/8YTxcuZC) (will be ready soon; the version will be 1.23.0)
