### ISSUE TITLE
Keyboard binding for Open File

### ISSUE THREAD

**Issue by permezel** [amake/orgro#57]
My iPadPro has a keyboard attached.  It would be nice if the file-open was tied to CMD-o, etc.
Also nice if I could just open a bunch of files and leave them open.  The standard keyboard bindings for navigating between multiple TABs (ala Safari) would also be nice.

**Comment by amake** [comment]
Please open separate issues for unrelated requests.

> Also nice if I could just open a bunch of files and leave them open.

This would require major rearchitecting of the UI, so I'm calling it out of scope for this ticket, which I have now narrowed to concern keyboard bindings only. Feel free to open a separate ticket.

**Comment by amake** [comment]
Keyboard shortcuts for open (Cmd/Ctrl+O) and close (Cmd/Ctrl+W) are available in 1.24.0.
