### ISSUE TITLE
Jump to search entries; 'Next' and 'Previous' buttons for search

### ISSUE THREAD

**Issue by SomeGitboi** [amake/orgro#65]
I understand how search works, but it would be more user-friendly if after searching for whatever text the user might search for, it jumps to the first entry. And if there are multiple entries of said text, the user then has the option to press a button that jumps to the next entry. There can also be another button for the previous entry.

**Comment by amake** [comment]
This would be nice to have. The main hurdle I have is that I don't know how to scroll a span of the document into view programmatically, except for [this method](https://stackoverflow.com/a/62988877/448068) which would be extremely onerous to implement given the current architecture where the Org document is rendered by a separate library.

**Comment by amake** [comment]
This will be available for beta testing shortly:

- iOS: https://testflight.apple.com/join/8YTxcuZC
- Android: https://play.google.com/store/apps/details?id=com.madlonkay.orgro

**Comment by amake** [comment]
This was released in v1.27.1.
