### ISSUE TITLE
How to grant access for relative links

### ISSUE THREAD

**Issue by 01abhishekjain** [amake/orgro#67]
I use Dropbox for syncing. My main org file contains multiple nested org files.

When I tap on Grant Access, an iOS file picker dialog thing opens up. What exactly am I supposed to do here?

Am I supposed to multiple select all the nested org files in the Dropbox folder from inside this dialog? If so, the problem is that Dropbox option is disabled. Please see attached image below.

![image](https://user-images.githubusercontent.com/11534188/193509311-794595ba-6ee4-4fa5-b8ec-5310428c699e.png)

**Comment by amake** [comment]
> What exactly am I supposed to do here?

You're supposed to tap Dropbox and select the "root" of the Dropbox hierarchy. But...

> the problem is that Dropbox option is disabled

Dropbox doesn't support the required APIs, so you simply can't use relative links with files stored in Dropbox. Please see the FAQ:
https://orgro.org/faq/#how-can-i-use-relative-links-between-org-mode-files

**Comment by 01abhishekjain** [comment]
Thanks for the comment. Unfortunately I cannot move from Dropbox so I have requested a refund.
