### ISSUE TITLE
Support for SVG

### ISSUE THREAD

**Issue by luk3ya0** [amake/orgro#74]
What about add svg ext support for image widget? Like the org babel plotting as svg file output in emacs

**Comment by luk3ya0** [comment]
<img width="640" alt="Screenshot 2023-05-07 at 08 35 25" src="https://user-images.githubusercontent.com/23734082/236651951-fb30aba6-1cbf-4c93-8add-847c6425a8dc.png">

**Comment by amake** [comment]
Do I understand correctly that the verbatim content of the `RESULTS` block is actually `[[file:./images/radial-tree.svg]]` (like if you were to view it in fundamental-mode)?

If so, then I can add rendering support for SVG but the ability of Orgro to access the file will be dependent on all of the stuff listed [here](https://orgro.org/faq/#how-can-i-use-relative-links-between-org-mode-files)

**Comment by luk3ya0** [comment]
yep, the output is actually a OrgFileLink

**Comment by luk3ya0** [comment]
![IMG_0927](https://user-images.githubusercontent.com/23734082/236657018-95192e46-acd4-4f6e-bcc6-16c9add47fc4.jpeg)

I try to get some points to approach, but svg image in flutter isn't mature as the binary ones.

**Comment by amake** [comment]
This will be available shortly for testing. Look for v1.28.1

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment]
@luk3ya0 I see you have some effort in your code to manipulate the size of the SVG image with `FittedBox`. That didn't seem necessary to me, but please let me know if the current sizing behavior needs improvement.

**Comment by luk3ya0** [comment]
I think it maybe useful to wrapped with `FittedBox` while the svg file coming from article documentclass (latex) with redundant white spaces, or outputted from inkscape with complicated path transformation. In that circumstance, the svg display fullfill the screen height.

**Comment by amake** [comment]
I think it will be hard to come up with a single strategy that gives good results in all cases. If there is a specific case where things need improvement, please open a new ticket with the specifics.

**Comment by luk3ya0** [comment]
ok, thanks for adding the improvement
