### ISSUE TITLE
Add Terminus font

### ISSUE THREAD

**Issue by MGadhvi** [amake/orgro#78]
Hello

Would you consider adding Terminus to the list of available fonts?

https://terminus-font.sourceforge.net/

**Comment by amake** [comment]
The original Terminus you linked to is only available in a format that I don't think works with Flutter.

However there is a TTF version that works: https://files.ax86.net/terminus-ttf/

**Comment by amake** [comment]
This will be available in v1.30.0. Look for it soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by MGadhvi** [comment]
Thank you for that!

**Comment by amake** [comment]
1.30.0 is now available on the App Store and Google Play. It should be on F-Droid whenever the next build cycle finishes.
