### ISSUE TITLE
Inline markup is dropped from titles

### ISSUE THREAD

**Issue by snowc0de** [amake/orgro#80]
For instance this:

```org
* Here's latex: \(\pi\)
And this is also latex \(\pi\)
```

Renders this:

![Screenshot_20230828_065705_com madlonkay orgro](https://github.com/amake/orgro/assets/33733474/63191747-c6ce-4c26-9ac2-1fbc76d0d55d)

As you can see, the Latex fragment in the title is completely ignored. And i'm using the 1.30.0 release from F-Droid.

**Comment by amake** [comment]
Titles are supposed to allow emphasis markup like `*bold*` and `/italic/` in addition to inline LaTeX; this is a bug in which only the first run of text is retained and all the rest is dropped.

**Comment by amake** [comment]
This will be available in v1.31.1. Look for it soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by snowc0de** [comment]
@amake That's really cool! Do you have any idea of when it will be released?

**Comment by amake** [comment]
Ideally I would get feedback from the beta and then release it. F-Droid doesn't have a facility for prereleases, so you'll have to either build from source or just wait.

Also F-Droid runs in cycles that I don't control, so even after I do my part it is unpredictable when it will actually be available on F-Droid.

**Comment by snowc0de** [comment]
@amake Thanks, I just managed to build it myself, it works nicely now ^^
