### ISSUE TITLE
Improve the TODO cycling UI

### ISSUE THREAD

**Issue by luk3ya0** [amake/orgro#82]
I appreciate that feature named cycle todo, but I think it's better to change the action to trigger the cycle todo. for instance slide the button left,  access the options.

Long pressing to narrow and swiping left to un-narrow is more intuitive.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by amake** [comment]
I agree that putting too much stuff under long-press is not very nice.

> slide the button left, access the options.

By "slide" do you mean like [this](https://m3.material.io/components/lists/guidelines#79546d3e-e897-4cfe-b842-664f6ad8750b)? Which button would you slide?

Right now the only thing that makes sense to slide is the headline. My concern with this is that the headline is too thin to reveal a reasonably sized control. Thus the entire section will have to slide, and that may interfere with other controls in the section.

**Comment by luk3ya0** [comment]
> By "slide" do you mean like [this](https://m3.material.io/components/lists/guidelines#79546d3e-e897-4cfe-b842-664f6ad8750b)? Which button would you slide?

Yes, exactly.

> My concern with this is that the headline is too thin to reveal a reasonably sized control. Thus the entire section will have to slide

Does it help to wrap the headline with another container and expanding the line height of headline?

**Comment by amake** [comment]
> Does it help to wrap the headline with another container and expanding the line height of headline?

I think it would be pretty weird for the headline to suddenly grow in size as you slide it. 

Otherwise the headline has to be taller than normal the entire time, which is a departure from the current "Orgro philosophy" of trying to display the document the same way Emacs would. I'll have to think about whether I want to go in that direction.

**Comment by luk3ya0** [comment]
All right, it does need to balance between precise control and consistent style.

**Comment by amake** [comment]
A promising widget package that might help implementing this: https://pub.dev/packages/flutter_slidable

**Comment by luk3ya0** [comment]
Sliding on org level button to reveal the operation, and long slide to narrow by default?

**Comment by amake** [comment]
> Sliding on org level button

Is "org level button" the headline?

I am looking at

- Long touch on headline to narrow (as before)
- Slide entire section to reveal additional actions (currently just "Cycle TODO")

**Comment by amake** [comment]
This will be in v1.35.0, which will be available for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment]
v1.35.2 is available for testing on iOS and Android.

**Comment by luk3ya0** [comment]
I appreciate that features on testing. It's great to long touch to narrow and slide to widen.

**Comment by amake** [comment]
v1.35.2 is now available on F-Droid as well.
