### ISSUE TITLE
Filter/search by TODO state

### ISSUE THREAD

**Issue by mkarup** [amake/orgro#86]
Sorry for asking this here, but is it possible to apply a filter to only show entries with e.g. the TODO state? 
I have a todo.org file that includes entries with both TODO and DONE state, because I only archive the DONE entries once in a while, at my PC. It would be nice to have a quick way to show my current todos. 

Thanks in advance, and thanks for the killer app, definitely the best viewing experience on Android.

**Comment by amake** [comment]
There isn't currently any sort of filtering capability. The closest you can get would be to cycle visibility to close everything, search for "TODO", and jump between search hits.

A filter is something that could be done; I think the main issues to think about are:

- What is filterable? Probably keywords and tags. What about arbitrary text? Anything else?
- What does the UI look like? How does it interact with other modes like search mode?

**Comment by amake** [comment]
Support for filtering the document into a "sparse tree" as in `org-sparse-tree` will be in v1.37.0, available for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by mkarup** [comment]
Thank you - this sounds awesome!
