### ISSUE TITLE
Support for Org-drill

### ISSUE THREAD

**Issue by Maddogskullcap** [amake/orgro#87]
I do not know if this would be possible, but if you were to add the ability to use Org-drill in Orgro it would be able to compete with Anki as a **mobile** spaced-repetition learning tool. Ankidroid cannot sync with plaintext files like the desktop app, It uses a a remote unsecure server to sync files and setting up a self-hosted server is not well documented, and of course it's not Org. If you could pull off mobile Org-drill in Orgro it'd be a major upgrade and could become a mainstream spaced-repetition learning tool.

**Comment by amake** [comment]
This would require reimplementing all of org-drill in Dart/Flutter. That's basically an entire, completely different app.

I am not planning on doing this, but I would accept patches for it.
