### ISSUE TITLE
Editing files

### ISSUE THREAD

**Issue by jdwoolc** [amake/orgro#88]
Is there a way to edit files? I know some changes can be saved, but I don't see a clear way to edit and add content to a file.

Edit: I want to add that if editing isn't a feature, it's not entirely clear that's the case. I would absolutely use this for so many tasks if I could edit documents, though -- todos, recipes, grocery lists...

**Comment by amake** [comment]
"Editing" is a large topic; previous discussion is here: #6. 

What you seem to want is freeform, full-text editing. The foundational (non-UI) work to allow that is complete, but it's not clear what kind of UI would make that sort of editing ergonomic on mobile.

**Comment by dougalcorn** [comment]
I'm not sure I understand the difficulty. What I'd like to see is a bi-modal edit action. Orgo has read and is displaying the file parsed and presented. Toggle to edit mode that puts the raw file in an edit buffer. Almost no-ui is needed or special rendering while typing. Edit in raw mode. Save and then orgo reloads the file and re-renders.

I'm sure I'm oversimplifying here. By far, Orgo's rendering and navigation of files is the best tool out there. I can use my iPad to read org files beautifully. I'd like to be able to fix typos, add sections, etc. I don't really want a full org-mode editor. I'm also not using this much for todos. It's mainly for note taking, journaling, studying.

**Comment by amake** [comment]
> I'm not sure I understand the difficulty. What I'd like to see is a bi-modal edit action

I guess the difficulty is that I've never considered that to be an acceptable editing experience. Ideally we would have one of:

- Fully "structured" GUI editing, like tapping a checkbox to toggle it, dragging list items to rearrange them, etc. This is not only difficult to program, but it's difficult to design appropriate controls and behaviors that expose all the things you might want to do
- Rich text editing, like with [Notion](https://www.notion.so/). The entire display is also an editable text field. If this is doable in Flutter, it would probably mean rebuilding the guts of Orgro from scratch.

Unfortunately I think I've let perfect be the enemy of good, so I will admit defeat for the time being on the above ideas, and just do the bi-modal editing thing.

v1.39.0 will be available with bi-modal editing shortly:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment]
This is now released on all platforms.
