### ISSUE TITLE
Can there be more sans font

### ISSUE THREAD

**Issue by wnear** [amake/orgro#89]
Sans vs Serif, I recently find sans font make reading on small sized device more efficiently, Serif like Times more suitable for publishing.

**Comment by amake** [comment]
I am willing to add some sans fonts, but Times is not available on Google Fonts.

Could you go to https://fonts.google.com/?stroke=Serif and find a few you like? Not all of them will be available for use in Flutter, but I'm sure many of them are.

**Comment by amake** [comment]
Sorry, I'm confused now. Do you want serif or sans fonts?

Most of the fonts I've made available in Orgro are monospace, which are often slab-serif fonts but not necessarily always. FiraGO is a notable exception being a proportional sans.

Regardless, the answer is the same: Go to the link above and find some you like, then let me know.

**Comment by amake** [comment]
The request is unclear. Feel free to clarify.
