### ISSUE TITLE
Support custom headline keywords

### ISSUE THREAD

**Issue by amake** [amake/orgro#93]
> @shelverizr Can you check https://github.com/amake/org_parser/pull/15 to confirm that that's what you had in mind?

@amake Not entirely, I want to switch from any keyword to any other keyword.

For example, I have two categories of tasks, to-do tasks and completed tasks, their keywords are:

To-do tasks: `TODO`, `NEXT`, `WAITING`, `MAYBE`
Completed tasks: `DONE`, `FAILED`, `SUCCESS`, `STUCK`, `SHUNT`

Sometimes I need to switch from `NEXT` to `TODO`
Sometimes I need to switch from `WAITING` to `MAYBE`
Sometimes I need to switch from `STUCK` to `NEXT`

_Originally posted by @shelverizr in https://github.com/amake/org_parser/issues/14#issuecomment-1975495377_

**Comment by unhammer** [comment]
This would be great. I just use one sequence `#+TODO: TODO HOLD DONE`

**Comment by amake** [comment]
The main difficulty with this is that the parser needs to know the desired keywords at parse time, so I need one of two things:

- A way for users to input the equivalent of `org-todo-keywords` as a global setting. But I don't have a settings screen, and I don't want to make one.
- Or, to parse the document, interpret `#+TODO:` (or `#+SEQ_TODO:` or `#+TYP_TODO:`), and then re-parse

**Comment by unhammer** [comment]
I'd vote for `#+TODO` being enough, that way if one syncs org files, the keyword list is trivially synced with them.

**Comment by amake** [comment]
Interpreting `#+TODO:` and related keywords is implemented in v1.41.0, available for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment]
v1.41.5 is now released
