### ISSUE TITLE
Add screen to select files from a directory

### ISSUE THREAD

**Issue by dotancohen** [amake/orgro#95]
The Orgro filepicker is good for using just a limited number of .org files spread around a filesystem. However, for the use case of storing all .org files in a directory and then browsing them, the current file picker is very cumbersome.

For such use case, please add a setting "Note base directory" and a screen that browses this directory. Thank you!

**Comment by amake** [comment]
By design Orgro only supports selecting a single file at a time. If you want to browse files, I suggest you use the file browser app that comes with your OS, and use it to open files in Orgro.

**Comment by dotancohen** [comment]
Will do, then, thank you.
