### ISSUE TITLE
Respect national settings for date format

### ISSUE THREAD

**Issue by rrgmitchell** [amake/orgro#99]
It would be good to see (where configured) European date format in file listings. Example, to me 8/6/2024 is the 8th of June, whereas OrgRo means it to be the 6th of August.

**Comment by amake** [comment]
I assume you're talking about the date shown under files on the start screen. On iOS for me this respects the locale that the app is run under: English, Japanese, or Ukranian. The app is not localized for other locales, so it will fall back to one of the above.

- What OS are you using? What version?
- What are your OS language settings? (Unless your OS version is ancient this should be a priority list of locales)

**Comment by rrgmitchell** [comment]
Hi Aaron,

Thanks for your quick response.

You're right that this is about the date next to previously opened files.

I am using OrgRo on an IPhone, with IOS 16.7.8. 

My 'Language and Region' in Settings has

*Region: United Kingdom**
*
*Date Format: 19/08/2024*

See attached screenshot.

I guess the English locale that the app uses must be US English, with US date format. I was hoping that formatting the date according to the region setting might be a relatively simple thing to do, but perhaps not. I am a developer, but not on mobile!

By the way, OrgRo is a superb app, the best for viewing org files on mobile that I have seen.

Best wishes,

Ron



----- Original message -----

**Comment by amake** [comment]
Unfortunately screenshots do not come through via email.

It looks like `en` locale is treated by the Flutter internationalization libraries as `en_US`. This looks solvable by supporting `en_GB` as well. The only spelling difference in any of the current Orgro strings appears to be "serialization" → "serialisation", so please do enjoy that 😄

**Comment by amake** [comment]
This should be fixed in v1.38.0, available for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment]
v1.38.0 is available for testing.

**Comment by amake** [comment]
v1.38.0 is released for iOS and Android

**Comment by rrgmitchell** [comment]
Many thanks for this change. I can now make sense of the dates on my files!

Best,

Ron
